title:              개발자 ymh의 블로그입니다
email:              ymh290229022gmail.com
description:        A Blog Theme by Start CodingStdy
author:             Start Bootstrap
baseurl:            "/ymh29022902-blog"
url:                "https://ymh29022902.github.io/ymh29022902-blog/"
future:              true
published:           true 

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
